# version: '3'

# services:
#   reverse:
#     container_name: reverse
#     hostname: reverse
#     image: nginx
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#       - ./nginx/conf:/etc/nginx
version: '3'

services:

  node-service:
    container_name: node-service
    build: ./node-app
    ports:
      - 3000:3000
    
  
  service-status-frontend:
    container_name: service_status_frontend
    image: nginx
    volumes:
      - ./service-status-frontend:/usr/share/nginx/html
    


  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - 80:80
    links:
      - node-service
      - service-status-frontend
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf